---
# tasks file for ansible-isc-dhcp-relay

- name: Debug OS Version
  debug:
    msg: "distribution: {{ ansible_distribution }}, major_version: {{ ansible_distribution_major_version }}"

- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- include: dhcrelay.yml
  when: (isc_dhcp_relay_run|bool)

- name: ISC-DHCP-Relay dead man's switch 
  debug:
    msg: "Skipped ISC-DHCP-Relay configuration because dead man's switch var 'isc_dhcp_relay_run' is not set to true"
  when: not isc_dhcp_relay_run|bool